import Header from './Header.jsx';  
import Footer from './Footer.jsx';  

function TermsOfService() {

    return(
        <main>
            <Header />
            <div className = "terms-of-service-container">

                <div className = "terms-of-service-contents">

                    <h2>Terms of Service</h2>
                    <p>This site and the mobile applications and services available in connection with this site and mobile application (the "App,” and our “Services") are made available to you by LGT Productions. ("LGT Productions", "We") subject to these Terms of Service, including those set forth in the Privacy Policy (the “Terms”). By accessing, using or downloading any materials from the App, you agree to follow and be bound by the Terms, which may be updated by us from time to time without notice to you. You can review the most current version of the Terms at any time at Terms of Use. We and our third-party providers may make improvements and/or changes in the products, services, mobile applications, features, programs, and prices described in this App at any time without notice. Certain provisions of the Terms may be supplemented or superseded by expressly designated legal notices or terms located on particular pages at this App. The App is not intended for and is not designed to attract children under 13 years of age. If you do not agree with the Terms, please do not use this App. BY CONTINUING TO USE THE APP, YOU ARE INDICATING YOUR AGREEMENT TO THE TERMS AND ALL REVISIONS THEREOF.</p>
                    <p>We reserve the right at any time and from time to time to modify or discontinue, temporarily or permanently, the App or any portion thereof with or without notice. You agree that we shall not be liable to you or to any third party for any modification, suspension or discontinuance of the App or any portion thereof.</p>
                    <h3>REGISTRATION</h3>
                    <p>To use some services available on the App, you must complete the membership registration form. You agree to: (a) provide true, accurate, current and complete information about yourself as prompted by the App’s registration form (“User Data”) and (b) maintain and promptly update the User Data to keep it accurate and current. You agree that we may use your User Data to provide services on the App for which you have expressed interest. If you provide any information that is inaccurate or not current, or we have reasonable grounds to suspect that such information is inaccurate or not current, we have the right to suspend or terminate your account and refuse any and all current or future use of the App. In consideration of your use of the App, you represent that you are of legal age to form a binding contract and are not a person barred from receiving services under the laws of any applicable jurisdiction.</p>
                    <h3>PAYMENTS</h3>
                    <p>If you choose to buy ArmBarn Pro, you must designate and provide information about your preferred payment method (e.g., credit card, online payment service, in-app purchase using your iTunes account, or any other payment method made available by us) (“Payment Method”). You will immediately be charged for these fees after you tap to buy ArmBarn Pro. You agree to pay all fees incurred in connection with your username and password for your ArmBarn account.</p>
                    <h3>FEES AND RENEWALS</h3>
                    <p>You may elect buy ArmBarn Pro and pay membership fees on an annual basis. All membership fees are payable in advance. Membership fees will be billed automatically to the Payment Method at the start of the annual period, as applicable, and will auto-renew until your membership is terminated. The renewal membership fees will be the same as the initial charges unless you are otherwise notified in advance. You authorize us to charge your Payment Method for the appropriate membership charges and fees and for any other purchases you elect to make via the App. We reserve the right to increase membership fees or to institute new fees at any time upon reasonable notice posted in advance on this App. If you upgrade your membership or add new categories of service to your account, such changes may result in a new billing date effective upon the date you elect such upgrade or addition. ALL PURCHASES ARE FINAL AND NO REFUND WILL BE GIVEN FOR UNUSED PORTIONS OF YOUR INITIAL OR ANY MEMBERSHIP PERIOD.</p>
                    <h3>CANCELLATION</h3>
                    <p>You may cancel ArmBarn Pro by visiting the subscription management options within iOS. The cancellation of a membership will go into effect at the end of your current billing cycle, and you will have the same level of access to the App through the remainder of such billing cycle. When your subscription ends, your account will enter free mode. No refunds or credits will be provided by us upon cancellation. You can renew your subscription at any time without opening a new account, provided that additional fees may apply if you decide to upgrade to ArmBarn Pro at a later date.</p>
                    <h3>USER CONDUCT</h3>
                    <p>You are solely responsible for maintaining the confidentiality of the password associated with your account and for restricting access to your password and to your computer while logged into the App. You accept responsibility for all activities that occur under your account or from your computer. We endeavor to use reasonable security measures to protect against unauthorized access to your account. We cannot, however, guarantee absolute security of your account, your Content or the personal information you provide, and we cannot promise that our security measures will prevent third-party “hackers” from illegally accessing the App or its contents. You agree to immediately notify us of any unauthorized use or your account or password, or any other breach of security, and to accept all risks of unauthorized access to the User Data and any other information you provide to us.</p>
                    <p>You understand that all information, data, text, software, sound, photographs, graphics, video, messages, tags, or other materials (“Content”), whether publicly posted or privately transmitted, available in connection with the App are the sole responsibility of the person from whom such Content originated. This means that you, and not us, are entirely responsible for all Content that you upload, post, email, transmit or otherwise make available via the App. We do not control or monitor the Content posted to the App by others and, as such, does not guarantee the accuracy, integrity or quality of such Content. You understand that by using the App, you may be exposed to Content that is offensive, indecent or objectionable. Under no circumstances will we be liable in any way for any Content, including, but not limited to, any errors or omissions in any Content, or any loss or damage of any kind incurred as a result of the use of any Content posted, emailed, transmitted or otherwise made available on the App.</p>
                    <p>You agree to not use the App to: (a) upload, post, email, transmit or otherwise make available any Content that is unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, invasive of another’s privacy, hateful, or racially, ethnically or otherwise objectionable; (b) harm minors in any way; (c) impersonate any person or entity, including, but not limited to, a LGT Productions official, forum leader, guide or host, or falsely state or otherwise misrepresent your affiliation with a person or entity; (d) upload, post, email, transmit or otherwise make available any Content that you do not have a right to make available under any law or under contractual or fiduciary relationships; (e) upload, post, email, transmit or otherwise make available any Content that infringes any patent, trademark, trade secret, copyright or other proprietary rights of any party; (f) upload, post, email, transmit or otherwise make available any unsolicited or unauthorized advertising, promotional materials, “junk mail,” “spam,” “chain letters,” “pyramid schemes,” or any other form of solicitation; (g) upload, post, email, transmit or otherwise make available any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; (h) interfere with or disrupt the App or servers or networks connected to the App, or disobey any requirements, procedures, policies or regulations of networks connected to the App; and/or (i) intentionally or unintentionally violate any applicable local, state, national or international law. You specifically agree not to access (or attempt to access) the App or the Content through any automated means (including the use of any script, web crawler, robot, spider, or scraper), and that you will not forge or manipulate identifiers in order to disguise the origin of any access (or attempted access) to the App. You must also obey all federal, state, and local laws, regulations and rules that apply to your activities when you use our Services and the App. We reserve the right to terminate your Account and to prevent your use of any and all our Services if your Account is used to engage in illegal activity or to violate this Terms of Service.</p>
                    <p>You acknowledge that we may or may not pre-screen or monitor Content, but that we and our designees shall have the right (but not the obligation) in their sole discretion to pre-screen, monitor, refuse or remove any Content that is available via the App. Without limiting the foregoing, we and our designees shall have the right to remove any Content that violates the Terms or is otherwise objectionable. You agree that you must evaluate, and bear all risks associated with, the use of any Content available in connection with the App, including any reliance on the accuracy, completeness, or usefulness of such Content.</p>
                    <p>You acknowledge, consent and agree that we may access, preserve and disclose your User Data, Payment Method information and other Content if required to do so by law or in a good faith belief that such access preservation or disclosure is reasonably necessary to: (a) comply with legal process; (b) enforce the Terms; (c) respond to claims that any Content violates the rights of third parties; (d) respond to your requests for customer service; or (e) protect the rights, property or personal safety of us, its users and the public. Subject to the foregoing, we will use reasonable efforts to maintain the confidentiality of your User Data and Payment Method information.</p>
                    <p>The App is for your personal and noncommercial use. You may not modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer or sell for any commercial purposes any portion of the App, use of the App or access to the App.</p>
                    <p>You understand that use of certain features of the App may require you to purchase third party equipment or materials. While we may recommend the equipment or materials of certain third-party suppliers, we shall have no responsibility for your acquisition or use of any third-party equipment or materials and does not guarantee that third party equipment or materials will function with the App or will be error-free.</p>
                    <h3>CONTENT SUBMITTED IN THE APP</h3>
                    <p>We do not claim ownership of Content you may submit or make available for inclusion on the App. However, with respect to Content you submit or make available for inclusion on the App, you grant us a worldwide, perpetual, irrevocable, royalty-free and non-exclusive license, as applicable, to use, distribute, reproduce, modify, adapt, publicly perform and publicly display and otherwise exploit such Content on the App for the purposes of providing and promoting the App and the features and services available on the App.</p>
                    <p>The App may provide you with the option of making certain Content that you submit to the App as private or available only to select users of the App. If, upon submission of Content to the App, you initially elect to mark such Content as private or available for a limited group of users, we will maintain the privacy of such Content in accordance with your election. However, if you do not elect to mark your Content as private or available for a limited group of users, or later change such designation to allow such Content to be made generally available, we cannot and does not guarantee the privacy of such Content.</p>
                    <h3>ELECTRONIC COMMUNICATIONS</h3>
                    <p>The App may provide you with the ability to send e-mails, post messages to user forums, enter chat rooms, speak via Internet voice connections or send similar messages and communications to third party service providers, advertisers, other users and/or us. You agree to use communication methods available on the App only to send communications and materials related to the subject matter for which we provided the communication method, and you further agree that all such communications by you shall be deemed your Content and shall be subject to and governed by the Terms. By using any of the communications methods available on the App, you acknowledge and agree that (a) all communications methods constitute public, and not private, means of communication between you and the other party or parties, (b) communications sent to or received from third party service providers, advertisers or other third parties are not be endorsed, sponsored or approved by us (unless expressly stated otherwise by LGT Productions) and (c) communications are not pre-reviewed, post-reviewed, screened, archived or otherwise monitored by us in any manner, though we reserve the right to do so at any time at its sole discretion in accordance with the Terms. You agree that all notices, disclosures and other communications that we provide to you electronically shall satisfy any legal requirement that such communications be in writing.</p>
                    <h3>PROPRIETARY RIGHTS</h3>
                    <p>You acknowledge and agree that the App, any necessary software used in connection with the App (if any) and any Content available on the App contain proprietary and confidential information that is protected by applicable intellectual property and other laws. Except as expressly permitted by applicable law or authorized by us or applicable third-party service providers or advertisers, you agree not to modify, rent, lease, loan, sell, distribute or create derivative works based on the App, the software or Content available on the App (other than Content that you may submit), in whole or in part.</p>
                    <p>We grant you a personal, non-transferable and non-exclusive right and license to access and use the App; provided that you do not (and do not allow any third party to) copy, modify, create a derivative work from, reverse engineer, reverse assemble or otherwise attempt to discover any source code, sell, assign, sublicense, grant a security interest in or otherwise transfer any right in the App. You agree not to access the App by any means other than through the interface that is provided by us for use in accessing the App.</p>
                    <p>The term ArmBarn, the ArmBarn logo and other LGT Productions logos and product and service names are the exclusive trademarks of, and are owned by, LGT Productions, and you may not use or display such trademarks in any manner without our prior written permission. Any third-party trademarks or service marks displayed on the App are the property of their respective owners.</p>
                    <p>We reserve all rights not expressly granted hereunder.</p>
                    <h3>DISCLAIMER OF WARRANTIES AND LIABILITY</h3>
                    <p>THE INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND CONTENT AVAILABLE ON THE APP IS PROVIDED TO YOU “AS IS” AND WITHOUT WARRANTY. LGT PRODUCTIONS AND ITS SUBSIDIARIES, AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS AND LICENSORS HEREBY DISCLAIM ALL WARRANTIES WITH REGARD TO SUCH INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND CONTENT, INCLUDING, WITHOUT LIMITATION, ALL IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NONINFRINGEMENT. LGT PRODUCTIONS AND ITS SUBSIDIARIES, AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS AND LICENSORS MAKE NO WARRANTY THAT (a) THE SERVICE WILL MEET YOUR REQUIREMENTS; (b) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE; (c) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE; (d) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS; AND (e) ANY ERRORS IN THE APP WILL BE CORRECTED.</p>
                    <p>YOU EXPRESSLY AGREE THAT LGT PRODUCTIONS IS NOT PROVIDING MEDICAL ADVICE VIA THE APP. THE CONTENT PROVIDED THROUGH THE APP, INCLUDING ALL TEXT, PHOTOGRAPHS, IMAGES, ILLUSTRATIONS, GRAPHICS, AUDIO, VIDEO AND AUDIO-VIDEO CLIPS, AND OTHER MATERIALS, WHETHER PROVIDED BY US OR BY OTHER ACCOUNT HOLDERS OR THIRD PARTIES IS NOT INTENDED TO BE AND SHOULD NOT BE USED IN PLACE OF (a) THE ADVICE OF YOUR PHYSICIAN OR OTHER MEDICAL PROFESSIONALS, (b) A VISIT, CALL OR CONSULTATION WITH YOUR PHYSICIAN OR OTHER MEDICAL PROFESSIONALS, OR (c) INFORMATION CONTAINED ON OR IN ANY PRODUCT PACKAGING OR LABEL. SHOULD YOU HAVE ANY HEALTH-RELATED QUESTIONS, PLEASE CALL OR SEE YOUR PHYSICIAN OR OTHER HEALTHCARE PROVIDER PROMPTLY. SHOULD YOU HAVE AN EMERGENCY, CALL YOUR PHYSICIAN OR 911 IMMEDIATELY. YOU SHOULD NEVER DISREGARD MEDICAL ADVICE OR DELAY IN SEEKING MEDICAL ADVICE BECAUSE OF ANY CONTENT PRESENTED ON THIS APP, AND YOU SHOULD NOT USE THE APP OR ANY CONTENT IN THE APP FOR DIAGNOSING OR TREATING A HEALTH PROBLEM. THE TRANSMISSION AND RECEIPT OF OUR CONTENT, IN WHOLE OR IN PART, OR COMMUNICATION VIA THE INTERNET, E-MAIL OR OTHER MEANS DOES NOT CONSTITUTE OR CREATE A DOCTOR-PATIENT, THERAPIST-PATIENT OR OTHER HEALTHCARE PROFESSIONAL RELATIONSHIP BETWEEN YOU AND LGT PRODUCTIONS.</p>
                    <p>YOU EXPRESSLY AGREE THAT YOUR ATHLETIC ACTIVITIES, WHICH GENERATE THE CONTENT YOU POST OR SEEK TO POST ON THE APP (INCLUDING BUT NOT LIMITED TO CYCLING) CARRY CERTAIN INHERENT AND SIGNIFICANT RISKS OF PROPERTY DAMAGE, BODILY INJURY OR DEATH AND THAT YOU VOLUNTARILY ASSUME ALL KNOWN AND UNKNOWN RISKS ASSOCIATED WITH THESE ACTIVITIES EVEN IF CAUSED IN WHOLE OR PART BY THE ACTION, INACTION OR NEGLIGENCE OF LGT PRODUCTIONS OR BY THE ACTION, INACTION OR NEGLIGENCE OF OTHERS. YOU ALSO EXPRESSLY AGREE THAT LGT PRODUCTIONS DOES NOT ASSUME RESPONSIBILITY FOR THE INSPECTION, SUPERVISION, PREPARATION, OR CONDUCT OF ANY RACE, CONTEST, GROUP RIDE OR EVENT THAT UTILIZES LGT PRODUCTION’S APP.</p>
                    <p>YOU EXPRESSLY AGREE TO RELEASE LGT PRODUCTIONS, ITS SUBSIDIARIES, AFFILIATES, OFFICERS, AGENTS, REPRESENTATIVES, EMPLOYEES, PARTNERS AND LICENSORS (THE “RELEASED PARTIES”) FROM ANY AND ALL LIABILITY CONNECTED WITH YOUR ATHLETIC ACTIVITIES, AND PROMISE NOT TO SUE THE RELEASED PARTIES FOR ANY CLAIMS, ACTIONS, INJURIES, DAMAGES, OR LOSSES ASSOCIATED WITH YOUR ATHLETIC ACTIVITIES. YOU ALSO AGREE THAT IN NO EVENT SHALL THE RELEASED PARTIES BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN ANY WAY CONNECTED WITH (a) YOUR USE OR MISUSE OF THE APP, (b) YOUR USE OR MISUSE OF EQUIPMENT OR PROGRAMS CREATED OR LICENSED BY LGT PRODUCTIONS WHILE ENGAGED IN ATHLETIC ACTIVITIES, (c) YOUR DEALINGS WITH THIRD PARTY SERVICE PROVIDERS OR ADVERTISERS AVAILABLE THROUGH THE APP, (d) ANY DELAY OR INABILITY TO USE THE APP EXPERIENCED BY YOU, (e) ANY INFORMATION, SOFTWARE, PRODUCTS, SERVICES OR CONTENT OBTAINED THROUGH THE APP, WHETHER BASED ON CONTRACT, TORT, STRICT LIABILITY OR OTHERWISE, EVEN IF LGT PRODUCTIONS HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES. BECAUSE SOME STATES/JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU.</p>
                    <h3>INDEMNIFICATION</h3>
                    <p>You agree to indemnify and hold us and our subsidiaries, affiliates, officers, agents, representatives, employees, partners and licensors harmless from any claim or demand, including reasonable attorneys’ fees, made by any third party due to or arising out of Content you submit, post, transmit or otherwise seek to make available through the App, your use of the App, your athletic activities which generate the Content you post or seek to post on the App (including, but not limited to, athletic activities in connection with any contests, races, group rides, or other events which our sponsors, organizes, participates in, or whose App is used in connection with), your connection to the App, your violation of the Terms, or your violation of any rights of another person or entity.</p>
                    <h3>TERMINATION</h3>
                    <p>You agree that we may, under certain circumstances and without prior notice, immediately terminate your account and/or access to the App. Cause for such termination shall include, but not be limited to, (a) breaches or violations of the Terms or other incorporated agreements or guidelines, (b) requests by law enforcement or other government agencies, (c) a request by you (self-initiated account deletions), (d) discontinuance or material modification to the App (or any portion thereof), (e) unexpected technical or security issues or problems, (f) extended periods of inactivity, and/or (g) nonpayment of any fees owed by you in connection with the App. Termination of your account may include (x) removal of access to all offerings within the App, (y) deletion of your information, files and Content associated with or inside your account, and (z) barring of further use of the App. Further, you agree that all terminations for cause shall be made in our sole discretion and that we shall not be liable to you or any third party for any termination of your account or access to the App.</p>
                    <h3>APPLICABLE LAWS</h3>
                    <p>This App is controlled by LGT Productions from its offices within the United States of America. We make no representation that the Content in the App or the App are appropriate or available for use in other locations, and access to them from territories where their content or use is illegal is prohibited. Those who choose to access this App from locations outside of the United States do so on their own initiative and are responsible for compliance with applicable local laws. You may not use or export the Content in violation of U.S. export laws and regulations.</p>
                    <h3>DISPUTE RESOLUTION BY BINDING ARBITRATION</h3>
                    <p>The purpose of this Section is to provide a streamlined method for resolution of disputes between us if they arise. PLEASE READ THIS CAREFULLY. IT AFFECTS YOUR RIGHTS.</p>
                    <p>Most customer concerns can be resolved quickly and to your satisfaction by contacting our customer support at lgtproductions@getarmbarn.com. In the unlikely event that we cannot resolve a concern to your satisfaction (or if we cannot resolve a concern we have with you after attempting to do so informally), then you and we agree to be bound by the following procedure to resolve any and all disputes between us. This provision applies to all consumers to the fullest extent allowable by law. By accepting these terms, you and we expressly waive the right to a trial by jury or to participate in a class action. This agreement is intended to be interpreted broadly. This Section covers any and all disputes between us (“Disputes”), including without limitation:</p>
                    <ul>
                        <li>claims arising out of or relating to any aspect of the relationship between us, whether based in contract, tort, statute, fraud, misrepresentation or any other legal theory;</li>
                        <li>claims that arose before this Agreement or any prior agreement (including, but not limited to, claims relating to advertising);</li>
                        <li>claims that are currently the subject of purported class action litigation in which you are not a member of a certified class; and</li>
                        <li>claims that may arise after the termination of this Agreement.</li>
                    </ul>
                    <p>References to "we," "you," and "us" include our respective subsidiaries, affiliates, agents, employees, predecessors in interest, successors, and assigns, as well as all authorized or unauthorized users or beneficiaries of services or Software under this or prior Agreements between us. This arbitration provision evidences a transaction in interstate commerce, and thus the Federal Arbitration Act governs the interpretation and enforcement of this provision. This arbitration provision shall survive termination of these Terms of Service.</p>
                    <p>Binding Arbitration. If you and we are unable to resolve a Dispute through informal negotiations, either you or we may elect to have the Dispute finally and exclusively resolved by binding arbitration. Any election to arbitrate by one party shall be final and binding on the other. YOU UNDERSTAND THAT BY THIS PROVISION, YOU AND we ARE FOREGOING THE RIGHT TO SUE IN COURT AND HAVE A JURY TRIAL. The arbitration shall be commenced and conducted under the Commercial Arbitration Rules of the American Arbitration Association (AAA) and, where appropriate, the AAA’s Supplementary Procedures for Consumer Related Disputes (AAA Consumer Rules), both of which are available at the AAA website www.adr.org. Your arbitration fees and your share of arbitrator compensation shall be governed by the AAA Rules and, where appropriate, limited by the AAA Consumer Rules. If such costs are determined by the arbitrator to be excessive, or if you send LGT Productions a notice indicating that you are unable to pay the fees required to initiate arbitration, then we will promptly pay all arbitration fees and expenses. The arbitration may be conducted in person, through the submission of documents, by phone, or online. The arbitrator will make a decision in writing and shall provide a statement of reasons if requested by either party. The arbitrator must follow applicable law, and any award may be challenged if the arbitrator fails to do so. You and we may litigate in court to compel arbitration, to stay proceeding pending arbitration, or to confirm, modify, vacate or enter judgment on the award entered by the arbitrator, only.</p>
                    <p><i>Restrictions.</i> You and we agree that any arbitration shall be limited to the Dispute between LGT Productions and you, individually. To the full extent permitted by law, (1) no arbitration shall be joined with any other; (2) there is no right or authority for any Dispute to be arbitrated on a class action-basis or to utilize class action procedures; and (3) there is no right or authority for any Dispute to be brought in a purported representative capacity on behalf of the general public or any other persons. YOU AND LGT PRODUCTIONS AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. Further, unless both you and we agree otherwise, the arbitrator may not consolidate more than one person's claims and may not otherwise preside over any form of a representative or class proceeding. If this specific provision is found to be unenforceable, then the entirety of this arbitration provision shall be null and void.</p>
                    <p><i>Location.</i> If you are a resident of the United States, arbitration will take place at any reasonable location convenient for you. For residents outside the United States, arbitration shall be initiated in the County of Pittsburgh, Commonwealth of Pennsylvania, United States of America, and you and we agree to submit to the personal jurisdiction of that court, in order to compel arbitration, to stay proceedings pending arbitration, or to confirm, modify, vacate or enter judgment on the award entered by the arbitrator.</p>
                    <p><i>Limitation on Arbitrator’s Authority.</i> The arbitrator may award declaratory or injunctive relief only in favor of the individual party seeking relief and only to the extent necessary to provide relief warranted by that party's individual claim.</p>
                    <p><i>Changes to This Provision.</i> Notwithstanding any provision in this Agreement to the contrary, we agree that if we make any future change to this arbitration provision (other than a change to the Notice Address), you may reject any such change by sending us written notice within 30 days of the change to the Arbitration Notice Address provided above. By rejecting any future change, you are agreeing that you will arbitrate any dispute between us in accordance with the language of this provision.</p>
                    <h3>ENTIRE AGREEMENT</h3>
                    <p>The Terms of Service (including the ArmBarn Privacy Policy and other Supplemental Terms incorporated by reference into this document) constitute the entire agreement between you and we relating to your rights and obligations in the use of we Services. If there is any conflict between the Terms of Service and any other rules or instructions posted on a we Service, we shall resolve the conflict in its sole discretion.</p>
                    <h3>NOTICE TO CALIFORNIA RESIDENTS</h3>
                    <p>Pursuant to Cal. Civil Code § 1789.3, please note that (a) LGT Productions is located at 550 Wood St., Suite 309, Pittsburgh, PA 15222, (b) The fees and charges for our Services vary depending on the services selected by you, and (c) If you have a complaint regarding the Services or desire further information on use of the Services, visit our Customer Support web pages at URL. For complaints, you may also contact the Complaint Assistance Unit of the Division of Consumer Services of the Department of Consumer Affairs in writing at 400 "R" Street, Sacramento, CA 95814 or by telephone at (916) 445-1254 or (800) 952-5210.</p>
                    <h3>GENERAL</h3>
                    <p>You agree that no joint venture, partnership, employment or agency relationship exists between you and LGT Productions as a result of the Terms or your use of the App. The Terms constitute the entire agreement between you and LGT Productions with respect to your use of the App. The failure of us to exercise or enforce any right or provision of the Terms shall not constitute a waiver of such right or provision. If any provision of the Terms is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties’ intentions as reflected in the provision, and the other provisions of the Terms remain in full force and effect. You may not assign, delegate or otherwise transfer your account or your obligations under these Terms without the prior written consent of us. We have the right, in its sole discretion, to transfer or assign all or any part of its rights under these Terms and will have the right to delegate or use third party contractors to fulfill its duties and obligations under these Terms and in connection with the App. Our notice to you via email, regular mail or notices or links on the App shall constitute acceptable notice to you under the Terms. A printed version of the Terms and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to the Terms to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. Section titles and headings in the Terms are for convenience only and have no legal or contractual effect. Any rights not expressly granted herein are reserved.</p>
                    <p>We will provide support to you related to the App via the following methods:</p>
                    <ul>
                        <li>Website https://getarmbarn.com</li>
                        <li>Email lgtproductions@getarmbarn.com</li>
                    </ul>
                    <p>LGT Productions strives to respond to support requests within 48 hours after the request is placed.</p>
                    <p>If you have any questions regarding these Terms, please contact us by email at lgtproductions@getarmbarn.com.</p>
                
                </div>
            </div>
            <Footer />
        </main>
        
    );

}

export default TermsOfService;